/* GENERATED by scripts/fetch-quotes.mjs from quran.com (Saheeh International)
   and sunnah.com. Do not edit by hand: change the entry in the script and run it again. */

export interface SourcedQuote {
  text: string
  source: string
  url: string
}

export const QUOTES_EN = {
  q3_19: {
    text: "Indeed, the religion in the sight of Allah is Islam.",
    source: "Ali 'Imran 3:19",
    url: "https://quran.com/3/19",
  },
  q2_163: {
    text: "And your god is one God. There is no deity [worthy of worship] except Him, the Entirely Merciful, the Especially Merciful.",
    source: "Al-Baqarah 2:163",
    url: "https://quran.com/2/163",
  },
  q21_107: {
    text: "And We have not sent you, [O Muhammad], except as a mercy to the worlds.",
    source: "Al-Anbya 21:107",
    url: "https://quran.com/21/107",
  },
  q4_103: {
    text: "Indeed, prayer has been decreed upon the believers a decree of specified times.",
    source: "An-Nisa 4:103",
    url: "https://quran.com/4/103",
  },
  q5_6_wudu: {
    text: "O you who have believed, when you rise to [perform] prayer, wash your faces and your forearms to the elbows and wipe over your heads and wash your feet to the ankles.",
    source: "Al-Ma'idah 5:6",
    url: "https://quran.com/5/6",
  },
  q5_6_tayammum: {
    text: "…and do not find water, then seek clean earth and wipe over your faces and hands with it.",
    source: "Al-Ma'idah 5:6",
    url: "https://quran.com/5/6",
  },
  q2_43: {
    text: "And establish prayer and give zakah and bow with those who bow [in worship and obedience].",
    source: "Al-Baqarah 2:43",
    url: "https://quran.com/2/43",
  },
  q2_43_short: {
    text: "And establish prayer and give zakah…",
    source: "Al-Baqarah 2:43",
    url: "https://quran.com/2/43",
  },
  q9_60: {
    text: "Zakah expenditures are only for the poor and for the needy and for those employed for it and for bringing hearts together [for Islam] and for freeing captives [or slaves] and for those in debt and for the cause of Allah and for the [stranded] traveler…",
    source: "At-Tawbah 9:60",
    url: "https://quran.com/9/60",
  },
  q9_103: {
    text: "Take, [O Muhammad], from their wealth a charity by which you purify them and cause them increase…",
    source: "At-Tawbah 9:103",
    url: "https://quran.com/9/103",
  },
  q2_183: {
    text: "O you who have believed, decreed upon you is fasting as it was decreed upon those before you that you may become righteous…",
    source: "Al-Baqarah 2:183",
    url: "https://quran.com/2/183",
  },
  q2_183_end: {
    text: "…that you may become righteous…",
    source: "Al-Baqarah 2:183",
    url: "https://quran.com/2/183",
  },
  q2_184: {
    text: "So whoever among you is ill or on a journey [during them] - then an equal number of other days [are to be made up].",
    source: "Al-Baqarah 2:184",
    url: "https://quran.com/2/184",
  },
  q2_187: {
    text: "And eat and drink until the white thread of dawn becomes distinct to you from the black thread [of night]. Then complete the fast until the night [i.e., sunset].",
    source: "Al-Baqarah 2:187",
    url: "https://quran.com/2/187",
  },
  q3_97: {
    text: "And [due] to Allah from the people is a pilgrimage to the House - for whoever is able to find thereto a way.",
    source: "Ali 'Imran 3:97",
    url: "https://quran.com/3/97",
  },
  q2_127: {
    text: "And [mention] when Abraham was raising the foundations of the House and [with him] Ishmael, [saying], \"Our Lord, accept [this] from us. Indeed, You are the Hearing, the Knowing.",
    source: "Al-Baqarah 2:127",
    url: "https://quran.com/2/127",
  },
  q2_127_short: {
    text: "…when Abraham was raising the foundations of the House and [with him] Ishmael…",
    source: "Al-Baqarah 2:127",
    url: "https://quran.com/2/127",
  },
  q2_158: {
    text: "Indeed, as-Safa and al-Marwah are among the symbols of Allah.",
    source: "Al-Baqarah 2:158",
    url: "https://quran.com/2/158",
  },
  q2_203: {
    text: "Then whoever hastens [his departure] in two days - there is no sin upon him; and whoever delays [until the third] - there is no sin upon him - for him who fears Allah.",
    source: "Al-Baqarah 2:203",
    url: "https://quran.com/2/203",
  },
  q2_203_short: {
    text: "Then whoever hastens [his departure] in two days - there is no sin upon him…",
    source: "Al-Baqarah 2:203",
    url: "https://quran.com/2/203",
  },
  q48_4: {
    text: "…that they would increase in faith along with their [present] faith.",
    source: "Al-Fath 48:4",
    url: "https://quran.com/48/4",
  },
  q33_56: {
    text: "Indeed, Allah confers blessing upon the Prophet, and His angels [ask Him to do so]. O you who have believed, ask [Allah to confer] blessing upon him and ask [Allah to grant him] peace.",
    source: "Al-Ahzab 33:56",
    url: "https://quran.com/33/56",
  },
  q2_144: {
    text: "And wherever you [believers] are, turn your faces [i.e., yourselves] toward it [in prayer].",
    source: "Al-Baqarah 2:144",
    url: "https://quran.com/2/144",
  },
  h_islam: {
    text: "Al-Islam implies that you testify that there is no god but Allah and that Muhammad is the messenger of Allah, and you establish prayer, pay Zakat, observe the fast of Ramadan, and perform pilgrimage to the (House) if you are solvent enough (to bear the expense of) the journey.",
    source: "Sahih Muslim 8a",
    url: "https://sunnah.com/muslim:8a",
  },
  h_islam_able: {
    text: "…perform pilgrimage to the (House) if you are solvent enough (to bear the expense of) the journey.",
    source: "Sahih Muslim 8a",
    url: "https://sunnah.com/muslim:8a",
  },
  h_iman: {
    text: "That you affirm your faith in Allah, in His angels, in His Books, in His Apostles, in the Day of Judgment, and you affirm your faith in the Divine Decree about good and evil.",
    source: "Sahih Muslim 8a",
    url: "https://sunnah.com/muslim:8a",
  },
  h_five: {
    text: "Islam is based on (the following) five (principles).",
    source: "Sahih al-Bukhari 8; Sahih Muslim 16",
    url: "https://sunnah.com/bukhari:8",
  },
  h_times: {
    text: "The time of the noon prayer is when the sun passes the meridian and a man's shadow is the same (length) as his height, (and it lasts) as long as the time for the afternoon prayer has not come; the time for the afternoon prayer is as long as the sun has not become pale; the time of the evening prayer is as long as the twilight has not ended; the time of the night prayer is up to the middle of the average night and the time of the morning prayer is from the appearance of dawn, as long as the sun has not risen…",
    source: "Sahih Muslim 612d",
    url: "https://sunnah.com/muslim:612d",
  },
  h_maghrib: {
    text: "…the time of the evening prayer is as long as the twilight has not ended…",
    source: "Sahih Muslim 612d",
    url: "https://sunnah.com/muslim:612d",
  },
  h_prayer_kufr: {
    text: "Between man and polytheism and unbelief is the abandonment of salat.",
    source: "Sahih Muslim 82b",
    url: "https://sunnah.com/muslim:82b",
  },
  h_salawat: {
    text: "He who blesses me once, Allah would bless him ten times.",
    source: "Sahih Muslim 408",
    url: "https://sunnah.com/muslim:408",
  },
  h_forgot: {
    text: "He who forgets the prayer, or he slept (and it was omitted), its expiation is (only) that he should observe it when he remembers it.",
    source: "Sahih Muslim 684c",
    url: "https://sunnah.com/muslim:684c",
  },
  h_wudu_forgiven: {
    text: "If anyone performs ablution like that of mine and offers a two-rak'at prayer during which he does not think of anything else (not related to the present prayer) then his past sins will be forgiven.",
    source: "Sahih al-Bukhari 159; Sahih Muslim 226",
    url: "https://sunnah.com/bukhari:159",
  },
  h_wudu_face: {
    text: "When a bondsman-a Muslim or a believer-washes his face (in course of ablution), every sin he contemplated with his eyes, will be washed away from his face along with water, or with the last drop of water…",
    source: "Sahih Muslim 244",
    url: "https://sunnah.com/muslim:244",
  },
  h_pray_as: {
    text: "Pray as you have seen me praying.",
    source: "Sahih al-Bukhari 631",
    url: "https://sunnah.com/bukhari:631",
  },
  h_sujud: {
    text: "I have been ordered to prostrate on seven bones i.e. on the forehead along with the tip of the nose and the Prophet (ﷺ) pointed towards his nose, both hands, both knees and the toes of both feet…",
    source: "Sahih al-Bukhari 812; Sahih Muslim 490",
    url: "https://sunnah.com/bukhari:812",
  },
  h_tashahhud: {
    text: "All the compliments, prayers and good things are due to Allah; peace be on you, O Prophet, and Allah's mercy and blessings [be on you]. Peace be on us and on the pious subjects of Allah. I testify that there is no Deity [worthy of worship] but Allah, and I testify that Muhammad is His slave and His Apostle.",
    source: "Sahih al-Bukhari 831; Sahih Muslim 402",
    url: "https://sunnah.com/bukhari:831",
  },
  h_fatiha: {
    text: "Whoever does not recite Al-Fatiha in his prayer, his prayer is invalid.",
    source: "Sahih al-Bukhari 756; Sahih Muslim 394",
    url: "https://sunnah.com/bukhari:756",
  },
  h_istiftah: {
    text: "Glorious You are O Allah, and with Your praise, and blessed is Your Name, and exalted is Your majesty, and none has the right to be worshipped but You.",
    source: "Jami' at-Tirmidhi 243; Sunan Abi Dawud 776",
    url: "https://sunnah.com/tirmidhi:243",
  },
  h_tasbih: {
    text: "Glory be to Allah, and praise be to Allah, and there is no god but Allah, and Allah is most great, and there is no might and no strength but in Allah.",
    source: "Sunan Abi Dawud 832",
    url: "https://sunnah.com/abudawud:832",
  },
  h_sadaqah: {
    text: "Charity does not decrease wealth.",
    source: "Sahih Muslim 2588",
    url: "https://sunnah.com/muslim:2588",
  },
  h_half_date: {
    text: "Save yourself from Hell-fire even by giving half a date-fruit in charity.",
    source: "Sahih al-Bukhari 1417; Sahih Muslim 1016",
    url: "https://sunnah.com/bukhari:1417",
  },
  h_no_zakah_horse: {
    text: "There is no Zakat either on a slave or on a horse belonging to a Muslim.",
    source: "Sahih al-Bukhari 1464; Sahih Muslim 982",
    url: "https://sunnah.com/bukhari:1464",
  },
  h_ramadan: {
    text: "Whoever observes fasts during the month of Ramadan out of sincere faith, and hoping to attain Allah's rewards, then all his past sins will be forgiven.",
    source: "Sahih al-Bukhari 38; Sahih Muslim 760",
    url: "https://sunnah.com/bukhari:38",
  },
  h_suhoor: {
    text: "Take Suhur as there is a blessing in it.",
    source: "Sahih al-Bukhari 1923; Sahih Muslim 1095",
    url: "https://sunnah.com/bukhari:1923",
  },
  h_iftar: {
    text: "The people will remain on the right path as long as they hasten the breaking of the fast.",
    source: "Sahih al-Bukhari 1957; Sahih Muslim 1098",
    url: "https://sunnah.com/bukhari:1957",
  },
  h_forget_fast: {
    text: "If somebody eats or drinks forgetfully then he should complete his fast, for what he has eaten or drunk, has been given to him by Allah.",
    source: "Sahih al-Bukhari 1933; Sahih Muslim 1155",
    url: "https://sunnah.com/bukhari:1933",
  },
  h_rubayyi: {
    text: "Since then we used to fast on that day regularly and also make our boys fast.",
    source: "Sahih al-Bukhari 1960; Sahih Muslim 1136",
    url: "https://sunnah.com/bukhari:1960",
  },
  h_talbiyah: {
    text: "I respond to Your call O Allah, I respond to Your call, and I am obedient to Your orders, You have no partner, I respond to Your call All the praises and blessings are for You, All the sovereignty is for You, And You have no partners with you.",
    source: "Sahih al-Bukhari 1549; Sahih Muslim 1184",
    url: "https://sunnah.com/bukhari:1549",
  },
  h_hajj_reborn: {
    text: "Whoever performs Hajj for Allah's pleasure and does not have sexual relations with his wife, and does not do evil or sins then he will return (after Hajj free from all sins) as if he were born anew.",
    source: "Sahih al-Bukhari 1521; Sahih Muslim 1350",
    url: "https://sunnah.com/bukhari:1521",
  },
  h_arafah: {
    text: "The Hajj is Arafah.",
    source: "Jami' at-Tirmidhi 889",
    url: "https://sunnah.com/tirmidhi:889",
  },
  h_rites: {
    text: "Learn your rituals (by seeing me performing them)…",
    source: "Sahih Muslim 1297",
    url: "https://sunnah.com/muslim:1297",
  },
  h_tashriq: {
    text: "The days of Tashriq are the days of eating and drinking and remembrance of Allah.",
    source: "Sahih Muslim 1141a, 1141b",
    url: "https://sunnah.com/muslim:1141a",
  },
  h_arafah_fast: {
    text: "I seek from Allah that fasting on the day of 'Arafa may atone for the sins of the preceding and the coming years…",
    source: "Sahih Muslim 1162a",
    url: "https://sunnah.com/muslim:1162a",
  },
} satisfies Record<string, SourcedQuote>

export type QuoteId = keyof typeof QUOTES_EN
