/* ============================================================
   Sound, synthesised. Zero bytes of audio ship with the app -
   every tone is generated by WebAudio at call time, so the
   "satisfying ding" costs nothing to load.

   Everything sits on a pentatonic scale, which has no dissonant
   interval, so sounds layered in any order still sound pleasant.
   ============================================================ */

let ctx: AudioContext | null = null
let master: GainNode | null = null
let enabled = true

export function setSound(on: boolean) {
  enabled = on
  if (master) master.gain.value = on ? 0.22 : 0
}

/** Browsers refuse to start audio before a gesture; call this from the
 *  first tap. Safe to call repeatedly. */
export function primeAudio() {
  if (ctx) {
    if (ctx.state === 'suspended') void ctx.resume()
    return
  }
  try {
    const AC = window.AudioContext ?? (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext
    ctx = new AC()
    master = ctx.createGain()
    master.gain.value = enabled ? 0.22 : 0
    master.connect(ctx.destination)
  } catch {
    ctx = null
  }
}

/** pentatonic degrees, in semitones from the root */
const PENTA = [0, 2, 4, 7, 9]
const note = (deg: number, octave = 0) =>
  523.25 * Math.pow(2, (PENTA[((deg % 5) + 5) % 5] + 12 * (octave + Math.floor(deg / 5))) / 12)

interface ToneOpts {
  freq: number
  at?: number
  dur?: number
  type?: OscillatorType
  gain?: number
  /** glide to this frequency across the note */
  to?: number
}

function tone({ freq, at = 0, dur = 0.16, type = 'sine', gain = 1, to }: ToneOpts) {
  if (!ctx || !master || !enabled) return
  const t0 = ctx.currentTime + at
  const osc = ctx.createOscillator()
  const g = ctx.createGain()
  osc.type = type
  osc.frequency.setValueAtTime(freq, t0)
  if (to) osc.frequency.exponentialRampToValueAtTime(to, t0 + dur)

  // fast attack, exponential decay - reads as "struck", not "faded in"
  g.gain.setValueAtTime(0.0001, t0)
  g.gain.exponentialRampToValueAtTime(gain, t0 + 0.008)
  g.gain.exponentialRampToValueAtTime(0.0001, t0 + dur)

  osc.connect(g)
  g.connect(master)
  osc.start(t0)
  osc.stop(t0 + dur + 0.02)
}

function noise(at = 0, dur = 0.12, gain = 0.35) {
  if (!ctx || !master || !enabled) return
  const t0 = ctx.currentTime + at
  const frames = Math.floor(ctx.sampleRate * dur)
  const buf = ctx.createBuffer(1, frames, ctx.sampleRate)
  const data = buf.getChannelData(0)
  for (let i = 0; i < frames; i++) data[i] = (Math.random() * 2 - 1) * (1 - i / frames) ** 2
  const src = ctx.createBufferSource()
  const g = ctx.createGain()
  const hp = ctx.createBiquadFilter()
  hp.type = 'highpass'
  hp.frequency.value = 2400
  g.gain.value = gain
  src.buffer = buf
  src.connect(hp)
  hp.connect(g)
  g.connect(master)
  src.start(t0)
}

/* ---------------- the palette ---------------- */

export const sfx = {
  /** every button */
  tap() {
    tone({ freq: note(2, 1), dur: 0.045, type: 'triangle', gain: 0.5 })
  },

  /** picking an option, placing a tile */
  select() {
    tone({ freq: note(3, 1), dur: 0.07, type: 'triangle', gain: 0.6 })
  },

  /** a right answer. rises with the streak so the 5th in a row
   *  genuinely sounds better than the 1st - that's the hook. */
  correct(streak = 0) {
    const lift = Math.min(streak, 6)
    tone({ freq: note(0 + lift, 1), dur: 0.1, type: 'sine', gain: 0.85 })
    tone({ freq: note(2 + lift, 1), at: 0.055, dur: 0.14, type: 'sine', gain: 0.8 })
    tone({ freq: note(4 + lift, 1), at: 0.105, dur: 0.22, type: 'sine', gain: 0.7 })
    noise(0.0, 0.07, 0.12)
  },

  /** kind, not punishing. a soft low thud, no buzzer. */
  wrong() {
    tone({ freq: 196, dur: 0.16, type: 'sine', gain: 0.7, to: 146 })
    tone({ freq: 98, dur: 0.2, type: 'triangle', gain: 0.35, to: 82 })
  },

  /** a pair snapping together */
  snap() {
    tone({ freq: note(4, 1), dur: 0.06, type: 'sine', gain: 0.7 })
    tone({ freq: note(2, 2), at: 0.04, dur: 0.1, type: 'sine', gain: 0.5 })
    noise(0, 0.05, 0.1)
  },

  /** lesson finished - the "conquered it" arpeggio */
  win() {
    ;[0, 1, 2, 3, 5].forEach((d, i) =>
      tone({ freq: note(d, 1), at: i * 0.075, dur: 0.34, type: 'sine', gain: 0.8 }),
    )
    tone({ freq: note(0, 2), at: 0.42, dur: 0.7, type: 'sine', gain: 0.75 })
    tone({ freq: note(2, 2), at: 0.44, dur: 0.7, type: 'sine', gain: 0.45 })
    noise(0.4, 0.4, 0.14)
  },

  /** a new step lights up on the stair */
  unlock() {
    tone({ freq: note(0, 0), dur: 0.5, type: 'sine', gain: 0.6, to: note(0, 2) })
    ;[0, 2, 4].forEach((d, i) =>
      tone({ freq: note(d, 2), at: 0.22 + i * 0.06, dur: 0.3, type: 'sine', gain: 0.45 }),
    )
    noise(0.2, 0.3, 0.12)
  },

  /** opening a chest */
  chest() {
    ;[0, 2, 4, 7].forEach((d, i) =>
      tone({ freq: note(d, 1), at: i * 0.05, dur: 0.5, type: 'sine', gain: 0.6 }),
    )
    noise(0, 0.5, 0.2)
  },

  /** streak counter ticking up */
  tick(i = 0) {
    tone({ freq: note(i, 2), dur: 0.05, type: 'sine', gain: 0.45 })
  },

  /** page / scene change */
  swoosh() {
    noise(0, 0.22, 0.1)
  },
}
