#!/usr/bin/env node
/* ============================================================
   Word-by-word meanings for every ayah in the course, fetched
   from quran.com, never written by hand.

     node scripts/fetch-glosses.mjs

   An English learner can hover (or tap) any Arabic word on an ayah
   card to see what it means, the way quran.com does. This reads
   each Arabic ayah card, finds its verse through the English twin's
   quran.com link, lines our words up with the verse's words, and
   writes src/core/content/glosses.quran.en.ts.

   The hadith glosses are written by hand in glosses.en.ts: there is
   no word-by-word source for them.
   ============================================================ */

import { build } from 'esbuild'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const content = path.join(HERE, '../src/core/content')
const OUT = path.join(content, 'glosses.quran.en.ts')
const tmp = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'siraj-')), 'lessons.mjs')

await build({
  stdin: { contents: `export { LESSONS } from './lessons'\nexport { LESSONS_EN } from './lessons.en'`, resolveDir: content, loader: 'ts' },
  bundle: true, format: 'esm', platform: 'node', outfile: tmp, logLevel: 'error',
})
const { LESSONS, LESSONS_EN } = await import(pathToFileURL(tmp).href)

/** the letters only: no vowel marks, no pause marks, one form of each letter */
const skeleton = (w) => w
  .replace(/[ؐ-ًؚ-ٰٟۖ-ۭـ]/g, '')
  .replace(/[ٱأإآ]/g, 'ا').replace(/ى/g, 'ي').replace(/ة/g, 'ه').replace(/ؤ/g, 'و').replace(/ئ/g, 'ي')
  .replace(/[^ء-ي]/g, '')

/** our words, split on spaces; a pause mark standing alone joins the word before it */
function words(text) {
  const out = []
  for (const t of text.split(/\s+/).filter(Boolean)) {
    if (!skeleton(t) && out.length) out[out.length - 1] += ' ' + t
    else out.push(t)
  }
  return out
}

/** transliteration marks folded to the letters the fonts carry */
const plain = (s) => s.normalize('NFD').replace(/[̀-ͯ]/g, '').normalize('NFC').replace(/\s+/g, ' ').trim()

function distance(a, b) {
  const d = Array.from({ length: a.length + 1 }, (_, i) => [i, ...Array(b.length).fill(0)])
  for (let j = 1; j <= b.length; j++) d[0][j] = j
  for (let i = 1; i <= a.length; i++)
    for (let j = 1; j <= b.length; j++)
      d[i][j] = Math.min(d[i - 1][j] + 1, d[i][j - 1] + 1, d[i - 1][j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1))
  return d[a.length][b.length]
}

async function verse(key) {
  const res = await fetch(`https://api.quran.com/api/v4/verses/by_key/${key}?words=true&word_fields=text_imlaei&language=en`)
  if (!res.ok) throw new Error(`quran.com ${key}: HTTP ${res.status}`)
  const data = await res.json()
  // one quran.com word can be two written words («يَا أَيُّهَا»): each
  // written word is kept, and remembers which word of the verse it is
  return data.verse.words
    .filter((w) => w.char_type_name === 'word')
    .flatMap((w, n) => words(w.text_imlaei ?? '').map((text) => ({ text, n, en: plain(w.translation.text) })))
}

const out = {}
for (const [id, lesson] of Object.entries(LESSONS)) {
  for (const card of lesson.cards) {
    if (card.kind !== 'quote' || card.of !== 'ayah') continue
    const twin = LESSONS_EN[id]?.cards.find((c) => c.id === card.id)
    const m = twin?.url?.match(/quran\.com\/(\d+)\/(\d+)/)
    if (!m) throw new Error(`${id} ${card.id}: the English card has no quran.com link`)
    const ours = words(card.text)
    const theirs = await verse(`${m[1]}:${m[2]}`)
    // where in the verse our excerpt starts: the offset whose words differ least
    let best = { at: -1, cost: Infinity }
    for (let at = 0; at + ours.length <= theirs.length; at++) {
      let cost = 0
      for (let i = 0; i < ours.length; i++) cost += distance(skeleton(ours[i]), skeleton(theirs[at + i].text))
      if (cost < best.cost) best = { at, cost }
    }
    if (best.at < 0 || best.cost > ours.length) {
      throw new Error(`${id} ${card.id}: could not line the words up with ${m[1]}:${m[2]} (cost ${best.cost})`)
    }
    // written words that are one word of the verse become one phrase
    const segs = []
    ours.forEach((ar, i) => {
      const w = theirs[best.at + i]
      const last = segs[segs.length - 1]
      if (last && last.n === w.n) last.ar += ' ' + ar
      else segs.push({ ar, en: w.en, n: w.n })
    })
    out[`${id}:${card.id}`] = segs.map(({ ar, en }) => ({ ar, en }))
  }
}

const body = Object.entries(out)
  .map(([k, segs]) => `  '${k}': [\n${segs.map((s) => `    { ar: ${JSON.stringify(s.ar)}, en: ${JSON.stringify(s.en)} },`).join('\n')}\n  ],`)
  .join('\n')
fs.writeFileSync(OUT, `/* GENERATED by scripts/fetch-glosses.mjs from quran.com's word-by-word English.
   Do not edit by hand: run the script again after changing an ayah card. */

import type { GlossSeg } from '../types'

export const QURAN_GLOSSES_EN: Record<string, GlossSeg[]> = {
${body}
}
`)
console.log(`wrote word-by-word meanings for ${Object.keys(out).length} ayat to ${path.relative(process.cwd(), OUT)}`)
